name: Test
on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.10.0'
      - name: Setup NPM
        working-directory: .
        run: |
          sudo npm install -g npm@10.2.5
      - name: Install packages
        working-directory: .
        run: |
          npm --prefix .github/workflows/ install
      - name: Download Ceramic
        working-directory: .
        run: |
          node .github/workflows/download-ceramic.js
      - name: Setup Haxe
        working-directory: .github/workflows/
        run: |
          export NEKOPATH=$PWD'/ceramic/git/haxe-binary/linux/neko'
          export HAXEPATH=$PWD'/ceramic/git/haxe-binary/linux/haxe'
          echo 'neko path: '$NEKOPATH
          echo 'haxe path: '$HAXEPATH
          sudo mkdir -p /usr/local/bin
          sudo mkdir -p /usr/local/lib
          sudo mkdir -p /usr/local/share/haxe
          sudo ln -s $HAXEPATH/haxe                 /usr/local/bin/haxe
          sudo ln -s $HAXEPATH/haxelib              /usr/local/bin/haxelib
          sudo ln -s $HAXEPATH/haxe-bin             /usr/local/bin/haxe-bin
          sudo ln -s $HAXEPATH/haxelib-bin          /usr/local/bin/haxelib-bin
          sudo ln -s $HAXEPATH/std                  /usr/local/share/haxe/std
          sudo ln -s $NEKOPATH/neko                 /usr/local/bin/neko
          sudo ln -s $NEKOPATH/nekoc                /usr/local/bin/nekoc
          sudo ln -s $NEKOPATH/nekoml               /usr/local/bin/nekoml
          sudo ln -s $NEKOPATH/nekotools            /usr/local/bin/nekotools
          sudo ln -s $NEKOPATH                      /usr/local/lib/neko
          sudo ln -s $NEKOPATH/libneko.so           /usr/local/lib/libneko.so
          sudo ln -s $NEKOPATH/libneko.so.2.3.0     /usr/local/lib/libneko.so.2.3.0
          sudo ln -s $NEKOPATH/libneko.so.2         /usr/local/lib/libneko.so.2
          sudo ldconfig
          sudo ldconfig /usr/local/lib
          echo 'neko: '$(neko -version)
          echo 'haxe: '$(haxe --version)
      - name: Install Ceramic
        working-directory: .github/workflows/ceramic/tools
        run: |
          ./ceramic link
      - name: Build 
        working-directory: test-app
        run: |
          ceramic clay build web --setup --assets --debug
